/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reflectiondemo;

import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author HASSAN
 */
public class ColorEidtPane extends javax.swing.JPanel {

    /**
     * Creates new form ColorEidtPane
     */
    public ColorEidtPane() {
        initComponents();
    }
private String name;
    public String showInputDialog(Component  parent, String init){
     renameField.setText(init);
        JOptionPane.showMessageDialog(parent, this,"Edit Favorite Color",JOptionPane.PLAIN_MESSAGE);
       
       
    return renameField.getText();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        renameButton = new javax.swing.JRadioButton();
        renameField = new javax.swing.JTextField();
        remove = new javax.swing.JRadioButton();
        removeAll = new javax.swing.JRadioButton();

        buttonGroup1.add(renameButton);
        renameButton.setText("Rename");

        buttonGroup1.add(remove);
        remove.setText("Remove");

        removeAll.setText("Remove All");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(renameButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(renameField, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(remove)
                        .addGap(31, 31, 31)
                        .addComponent(removeAll)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(renameButton)
                    .addComponent(renameField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remove)
                    .addComponent(removeAll))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    protected javax.swing.JRadioButton remove;
    protected javax.swing.JRadioButton removeAll;
    protected javax.swing.JRadioButton renameButton;
    private javax.swing.JTextField renameField;
    // End of variables declaration//GEN-END:variables
}
